[package]
name = "{{project-name}}-store-memory"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "{{project-description}}: in-memory item repository"

[dependencies]
async-trait.workspace = true
domain.workspace = true
uuid.workspace = true

[dev-dependencies]
testkit.workspace = true
tokio.workspace = true

[lib]
name = "store_memory"
