[package]
name = "{{project-name}}-store-sqlx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "{{project-description}}: {{store}} item repository"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
domain.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
testkit.workspace = true
tokio.workspace = true

[lib]
name = "store_sqlx"
