[package]
name = "hexagonal-generated-domain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "An example generated using the hexagonal template: entities, rules and ports"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lib]
name = "domain"
