#!/bin/ksh
#
# $OpenBSD$

daemon="/usr/local/sbin/{{daemon_name}}"

. /etc/rc.d/rc.subr

rc_configtest() {
	${daemon} -n ${daemon_flags}
}

rc_reload() {
	/usr/local/sbin/{{ctl_name}} reload
}

rc_cmd $1
