#!/bin/ksh
#
# $OpenBSD$

daemon="/usr/local/sbin/daemon-generatedd"

. /etc/rc.d/rc.subr

rc_configtest() {
	rc_exec "${daemon} -n ${daemon_flags}"
}

rc_reload() {
	/usr/local/sbin/daemon-generatedctl reload
}

rc_cmd $1
