[package]
name = "{{project-name}}-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "{{project-description}}: command line client"

[dependencies]
anyhow.workspace = true
application.workspace = true
clap.workspace = true
dotenvy.workspace = true
store_sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
