[template]
cargo_generate_version = ">=0.21.1"
ignore = ["Cargo.lock", "target"]

[hooks]
pre = ["hooks/pre.rhai"]

[placeholders]
project-description = { type = "string", prompt = "Short description", default = "Command line tool" }
gh-username = { type = "string", prompt = "GitHub username (repository URL, FUNDING.yml)" }
domain = { type = "string", prompt = "Domain for security/conduct contact emails", default = "example.org" }
args = { type = "string", prompt = "Argument parser", choices = ["getopt", "clap"], default = "getopt" }
config = { type = "bool", prompt = "TOML configuration file?", default = false }
dotenv = { type = "bool", prompt = "Load .env with dotenvy?", default = false }
